name: Backend CI

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development
    env:
      working-directory: ./back-end
      DB_URL: ${{ secrets.DB_URL }}
      TESTDB_URL: ${{ secrets.TESTDB_URL }}
      PORT: ${{ secrets.PORT }}


    # steps:
    # - uses: actions/checkout@v2
    # - name: Setup Node.js 
    #   uses: actions/setup-node@v2

    # - name: Install backend dependencies
    #   working-directory: ./back-end
    #   run: npm ci
      
    # - name: Run backend tests
    #   working-directory: ./back-end
    #   run: npm test
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install backend dependencies
      working-directory: ./back-end
      run: npm ci

    - name: Run backend tests
      working-directory: ./back-end
      run: npm test