# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend CI

on:
  push:
    branches: [ "develop" , "master" ]
  pull_request:
    branches: [ "develop" , "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development
    env:
      working-directory: ./front-end

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js 
      uses: actions/setup-node@v2

    - name: Install frontend dependencies
      working-directory: ./front-end
      run: npm ci
      
    - name: Run frontend tests
      working-directory: ./front-end
      run: npm test